const interviews = [
  {
    name: 'subak',
    fullName: 'Abby Subak',
    title: 'Artist',
    videoPath: 'https://player.vimeo.com/video/231733376',
    imagePath: 'jpg/subak.jpg',
    category: 'Social Landscape',
    description: 'Abby is an artist and the Executive Director of Arts Gowanus, a local non-profit organization working to support, promote, and advocate for local artists and a sustainable arts community. Each year the organization sponsors Gowanus Open Studios, an event held in October that showcases local artists and their work, connecting them to the greater New York City community.',
    layers: ['assessedValue', 'galleries', 'watershed'],
    quote: 'There’s a reason gowanus has become such a hub of creativity and artists’ culture, and that’s because of the affordable spaces that are here, and it’s because of the history of industry and manufacturing that has been going on in Gowanus for a couple hundred years now.',
  },
  {
    name: 'basile',
    fullName: 'Paul Basile',
    title: 'Developer',
    videoPath: 'https://player.vimeo.com/video/231579159',
    imagePath: 'jpg/basile.jpg',
    category: 'Industry and Infrastructure',
    description: 'A property manager and developer, Paul founded Gowanus Alliance in 2010 with three friends, all second and third generation businessmen in the surrounding area. Paul promotes the retention of manufacturing, industrial, creative, and entertainment businesses in the Gowanus community; seeks a new location for the Kentile sign he rescued prior to its demolition; and advocates for new community playgrounds and parks.',
    layers: ['manufacturingLandUse', 'plutoBounds'],
    quote: 'We need more of the same. We need more space for the manufacturers to feel comfortable that they can grow into a 5 or 10 year plan.',
  },
  {
    name: 'pinkard',
    fullName: 'Tracey Pinkard',
    title: 'Gowanus Houses Art Collective',
    videoPath: 'https://player.vimeo.com/video/231577629',
    imagePath: 'jpg/pinkard.jpg',
    category: 'Community',
    description: 'While working as Parent Coordinator at the Brooklyn School of Collaborative Studies, Tracey co-founded the Gowanus Houses Art Collective, an arts youth program for the complex where she is a long time resident. She sees the program as a bridge to the creative community in the surrounding wealthier neighborhoods, offering them a window into life in the public housing complex.',
    layers: ['cleanup'],
    quote: 'For many years the canal reeked, the smell was just horrible, and in the summer it permeated, it was just sickening. And so now there’s this superfund, and there’s this big concern about the cleanup.',
  },
  {
    name: 'uz',
    fullName: 'Michelle de la Uz',
    title: 'Fifth Avenue Committee',
    videoPath: 'https://player.vimeo.com/video/231577261',
    imagePath: 'jpg/uz.jpg',
    category: 'Equity',
    description: 'Michelle is the Executive Director of the Fifth Avenue Committee, a non-profit community organization in Brooklyn that develops and manages affordable housing and community facilities, creates economic opportunities and ensures access to economic stability, organizes residents and workers, offers student-centered adult education, and combats displacement caused by gentrification. She also serves on the New York City Planning Commission.',
    layers: ['zoning', 'plutoBounds'],
    quote: 'I think that the cleanup processes that are underway and the rezoning that will be formally launched have the ability to try to right some wrongs that have existed historically, but I think that only happens if we are conscious about righting those wrongs.',
  },
];

export default interviews;
